#!/bin/bash

if [ "$#" -ne 2 ]; then 
	echo "There must be two parameters!" >&2
	exit 1
fi

if [ ! -f "$1" ]; then
	echo "The first parameter must be a file!" >&2
	exit 2
fi

if [ -f "$2" ]; then
	echo "The third parameter mustn't be an existing file!" >&2
	exit 3
fi

if [ ! -r "$1" ]; then 
	echo "The file must be readable!" >&2
	exit 4
fi

touch "$2"

cut -d ',' -f 2- "$1" | sort | uniq -c | awk '$1 < 2 {print $2}' | while read line; do
	cat "$1" | cut -d ',' -f 2- | egrep -w "$line" >> $2
done


cut -d ',' -f 2- "$1" | sort | uniq -c | awk '$1 > 1 {print $2}' | while read line; do
	egrep "$line" "$1" | sort -t ',' -nk 1 | tail -n +2 | xargs -I {} sed -i "s/{}//g" "$1"
done

exit 0
